/* eslint-disable import/prefer-default-export */
export const actionTypes = {
  SET_SELECTED_ELEMENTS: 'SET_SELECTED_ELEMENTS',
  SET_SAVED_ELEMENTS: 'SET_SAVED_ELEMENTS',
  SET_PREVIOUS_SAVED_ELEMENTS: 'SET_PREVIOUS_SAVED_ELEMENTS',
  RESET_WIDGET_VALUE: 'RESET_WIDGET_VALUE',
  SAVE_WIDGET_VALUE: 'SAVE_WIDGET_VALUE',
};
